### ISSUE TITLE
Store processes and steps using Doctrine

### ISSUE THREAD

**Issue by Spomky** [lexik/LexikWorkflowBundle#20]
At this moment, processes and steps are stored in the confiugration.
Is it possible to store processes and steps using Doctrine?

**Comment by cedric-g** [comment]
Hi, it's not impossible to do, but it's not a little change.
We use configuration files because we create some service on the fly in the bundle's extension class. Using a database as source to load the config would require to trigger an early query to get the workflow config while Symfony is loading the bundle (so by creating manually a PDO connection as the container is still under construction).

**Comment by Warks** [comment]
Hi,
Maybe it will be more easier to manage them into the Class file. any ideas to do that ?
